Add limit to start ticket auto buyer grpc call
decred/dcrwallet pull request #1816
Opened 2020-08-14 17:28 UTC by vctt94

Right now, when starting the ticket auto buyer by a grpc command, a limit to buy ticket is not set, which can cause a double spend if using a vspd. 

This PR adds a limit param, so we can avoid that.

2020-08-14 18:23 UTC, jrick commented
Why would not setting a limit cause a double spend? that sounds like another bug entirely

2020-10-15 14:00 UTC, jrick requested changes

2020-10-15 14:06 UTC, vctt94 commented on internal/rpc/rpcserver/server.go
> +	}
I kept the variable so we can keep the comment

2020-10-15 14:07 UTC, jrick approved these changes

2020-10-15 14:07 UTC, merged