Set tspend & treasury policies on VSP
decred/dcrwallet pull request #2135
Opened 2022-02-02 16:32 UTC by jholdstock

This PR ensures tspend and treasury voting preferences are sent to VSPs. This occurs when tickets are initially purchased, or when preferences are changed via RPC.

2022-02-02 18:51 UTC, jrick commented
needs rebase

2022-02-02 18:55 UTC, jrick commented on internal/rpc/jsonrpc/methods.go
> +		return nil, err
ticketHash could be nil here, and besides, I don't think we want to be returning errors for any tickets that were bought solo

2022-02-02 19:50 UTC, jholdstock commented
Rebased and introduced func `jsonrpc.Server.updateVSPVoteChoices` to reduce the amount of duplicated code between the 3 vote choice RPCs.

2022-02-09 17:05 UTC, jrick requested changes

2022-02-09 17:07 UTC, jholdstock commented on wallet/wallet.go
> +func (w *Wallet) SetAgendaChoices(ctx context.Context, ticketHash *chainhash.Hash, choices []AgendaChoice) (voteBits uint16, err error) {
Done

2022-02-09 17:37 UTC, jrick approved these changes

2022-02-09 17:38 UTC, merged