multi: Hard-code background context for vsp client
decred/dcrwallet pull request #2252
Opened 2023-06-24 10:27 UTC by jholdstock

The VSP client code was not handling contexts correctly. It was receiving short-lived contexts bound to the lifespan of a single RPC request, and using them for long-lived tasks.

This change fixes that specific problem by hard-coding the VSP client code to use context.Background everywhere.

Closes #2239

2023-06-26 19:54 UTC, jrick requested changes
I don't think that we should remove the context from these apis.  Instead, anywhere we don't want the request context to encapsulate the vsp client's management of the ticket (like ProcessTicket) we should pass context.Background() explicitly.  There are also some spots (like SetVoteChoice) where I do think that the request context encapsulates the vsp client's actions, so there we would still pass in the rpc context.

2023-06-30 13:58 UTC, jholdstock commented
I've reworked this PR to keep context in the API (and included a few other minor nits I noticed along the way - sorry!)

After taking a much closer look at the use of contexts, it turns out that only the methods of feePayment are running async, so we can just pass background context into that. Everything else can remain as-is.

2023-06-30 14:19 UTC, jrick commented
Ok, I think i prefer that better as well, as it leaves the wallet methods called by feePayment still using the rpc request context, which is good for tracing the db calls performed by rpc methods (among other reasons).

2023-06-30 14:19 UTC, jrick approved these changes

2023-06-30 14:19 UTC, merged