chore: make function comment match function names
decred/dcrwallet pull request #2382
Opened 2024-06-14 10:22 UTC by tongjicoder

2025-03-30 09:33 UTC, jholdstock approved these changes

2025-03-31 14:12 UTC, jrick requested changes

2025-05-27 06:28 UTC, tongjicoder commented on rpc/client/dcrwallet/methods.go
>  func (c *Client) GetInfo(ctx context.Context) (*types.InfoWalletResult, error) {
The changes here have been fixed in other PRs.

Revert. Please review again.

2025-05-27 06:28 UTC, tongjicoder commented
@jrick Sorry for so long to deal with it, please review again.

2025-05-27 13:35 UTC, jrick requested changes

2025-05-27 13:35 UTC, jrick commented on rpc/jsonrpc/types/methods.go
> -	"github.com/decred/dcrd/dcrjson/v4"
it won't compile without this.

2025-05-27 14:27 UTC, tongjicoder commented on rpc/jsonrpc/types/methods.go
> -	"github.com/decred/dcrd/dcrjson/v4"
Oh, it's been reverted. It should have been automatically removed by my IDE. 

However, I searched for the keyword 'v4' and there are indeed calls to 'v4.' in the current file.

2025-05-27 14:30 UTC, merged